name: Test task Node.js CI

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm test -- --watch=false    
    - name: Upload artifact of build job
      uses: actions/upload-artifact@v3
      with:
        name: art
        path: dist
          
  package:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [build]
    
    steps:
    - uses: actions/checkout@v2
    - name: Download art
      uses: actions/download-artifact@v3
      with:
        name: art
        path: ./docker/dist
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Package and push
      uses: docker/build-push-action@v2
      with:
        context: ./docker/
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  
