# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Node.js CI

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm test -- --watch=false    
    - name: Upload artifact of build job
      uses: actions/upload-artifact@v3
      with:
        name: art
        path: dist
          
  package:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [build]
    
    steps:
    
    - name: Download art
      uses: actions/download-artifact@v3
      with:
        name: art
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Debug
      run: |
        echo ---pwd---
        pwd
        echo ---ls -la---
        ls -la
        echo ---ls -l /home/runner/work/angular-starter/angular-starter---
        ls -l /home/runner/work/angular-starter/angular-starter
        echo ---ls -l /home/runner/work/angular-starter/angular-starter/angular-starter---
        ls -l /home/runner/work/angular-starter/angular-starter/angular-starter
        echo ---tree .---
        tree .
        
    
